apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7z7u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7z7u
    app.kubernetes.io/part-of: load-app-09d0b2bf-7d1a-47d5-8974-18c125fb5bad
  name: devfile-sample-7z7u
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-7z7u
status:
  loadBalancer: {}
